//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entities
{
    public partial class tipoformato
    {
        public tipoformato()
        {
            this.formato = new HashSet<formato>();
        }
    
        public int codigotipo { get; set; }
        public string nombretipo { get; set; }
    
        public virtual ICollection<formato> formato { get; set; }
    }
    
}
