//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entities
{
    public partial class usuariocia
    {
        public int idusercia { get; set; }
        public int idcompania { get; set; }
        public int idusuario { get; set; }
    
        public virtual sucursal sucursal { get; set; }
        public virtual usuario usuario { get; set; }
    }
    
}
