//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entities
{
    public partial class compania
    {
        public compania()
        {
            this.sucursal = new HashSet<sucursal>();
            this.conexuser = new HashSet<conexuser>();
        }
    
        public int idcompania { get; set; }
        public string nombrecia { get; set; }
        public string nit { get; set; }
        public string digito { get; set; }
    
        public virtual ICollection<sucursal> sucursal { get; set; }
        public virtual ICollection<conexuser> conexuser { get; set; }
    }
    
}
