//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entities
{
    public partial class datosusuario
    {
        public datosusuario()
        {
            this.usuario = new HashSet<usuario>();
        }
    
        public int idusuariodat { get; set; }
        public string cedula { get; set; }
        public string nombresusuario { get; set; }
        public string apellidosusuario { get; set; }
        public string telefonousuario { get; set; }
        public string direccionusuario { get; set; }
    
        public virtual ICollection<usuario> usuario { get; set; }
    }
    
}
