//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entities
{
    public partial class formaspago
    {
        public int idformaspago { get; set; }
        public string codformaspago { get; set; }
        public string nombreforma { get; set; }
        public bool sivence { get; set; }
    }
    
}
