//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entities
{
    public partial class maecli
    {
        public int codigocli { get; set; }
        public int idcliente { get; set; }
        public string facturanombre { get; set; }
        public bool bloqueado { get; set; }
        public string direccionenvio { get; set; }
        public int plazo { get; set; }
        public decimal cupo { get; set; }
        public decimal descuento { get; set; }
        public string regimen { get; set; }
        public bool grancotribu { get; set; }
        public Nullable<decimal> ppago1 { get; set; }
        public Nullable<decimal> ppago2 { get; set; }
        public bool causareteica { get; set; }
        public bool aplicareteica { get; set; }
        public bool causareteiva { get; set; }
        public bool descuentareteiva { get; set; }
        public bool retexcomprar { get; set; }
        public bool descontretenvend { get; set; }
        public Nullable<decimal> porretencion { get; set; }
        public string jefecompra { get; set; }
        public string comprador { get; set; }
        public int cuenta { get; set; }
        public int idvendedor { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual maeconta maeconta { get; set; }
        public virtual vendedor vendedor { get; set; }
    }
    
}
