//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entities
{
    public partial class maenits
    {
        public maenits()
        {
            this.acucentr = new HashSet<acucentr>();
            this.maeconta = new HashSet<maeconta>();
            this.movimi = new HashSet<movimi>();
            this.maepagos = new HashSet<maepagos>();
            this.maetribut = new HashSet<maetribut>();
        }
    
        public int idnit { get; set; }
        public int idtiponit { get; set; }
        public string nit { get; set; }
        public string digito { get; set; }
        public string nombrenit { get; set; }
        public int idciudad { get; set; }
        public string acteconomic { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string celular { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<acucentr> acucentr { get; set; }
        public virtual ciudad ciudad { get; set; }
        public virtual ICollection<maeconta> maeconta { get; set; }
        public virtual ICollection<movimi> movimi { get; set; }
        public virtual ICollection<maepagos> maepagos { get; set; }
        public virtual ICollection<maetribut> maetribut { get; set; }
        public virtual tiponit tiponit { get; set; }
    }
    
}
