//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entities
{
    public partial class maetrac
    {
        public maetrac()
        {
            this.movimi = new HashSet<movimi>();
        }
    
        public int idtransaccion { get; set; }
        public string codigotrac { get; set; }
        public int idmoduloppal { get; set; }
        public string nombretrac { get; set; }
        public string afectasaldo { get; set; }
        public bool afectaotro { get; set; }
        public bool generaasiento { get; set; }
        public bool consecutivo { get; set; }
        public Nullable<int> numeroactual { get; set; }
        public Nullable<int> codigcomp { get; set; }
    
        public virtual comprobante comprobante { get; set; }
        public virtual moduloppal moduloppal { get; set; }
        public virtual ICollection<movimi> movimi { get; set; }
    }
    
}
