//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entities
{
    public partial class saldospagos
    {
        public int idsaldospagos { get; set; }
        public int idsucursal { get; set; }
        public int idnit { get; set; }
        public string cuenta { get; set; }
        public string mes { get; set; }
        public string anio { get; set; }
        public decimal saldo { get; set; }
        public decimal movimiento { get; set; }
    
        public virtual maeconta maeconta { get; set; }
        public virtual maenits maenits { get; set; }
        public virtual sucursal sucursal { get; set; }
    }
    
}
