//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entities
{
    public partial class sucursal
    {
        public sucursal()
        {
            this.acucentr = new HashSet<acucentr>();
            this.inflacion = new HashSet<inflacion>();
            this.maepagos = new HashSet<maepagos>();
            this.movimi = new HashSet<movimi>();
            this.presupuesto = new HashSet<presupuesto>();
            this.saldoscuentas = new HashSet<saldoscuentas>();
            this.usuariocia = new HashSet<usuariocia>();
            this.vendedor = new HashSet<vendedor>();
        }
    
        public int idsucursal { get; set; }
        public int idcompania { get; set; }
        public string nombresucursal { get; set; }
        public int idciudad { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string paginaocorreo { get; set; }
    
        public virtual ICollection<acucentr> acucentr { get; set; }
        public virtual ciudad ciudad { get; set; }
        public virtual compania compania { get; set; }
        public virtual ICollection<inflacion> inflacion { get; set; }
        public virtual ICollection<maepagos> maepagos { get; set; }
        public virtual ICollection<movimi> movimi { get; set; }
        public virtual ICollection<presupuesto> presupuesto { get; set; }
        public virtual ICollection<saldoscuentas> saldoscuentas { get; set; }
        public virtual ICollection<usuariocia> usuariocia { get; set; }
        public virtual ICollection<vendedor> vendedor { get; set; }
    }
    
}
