//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entities
{
    public partial class usuario
    {
        public usuario()
        {
            this.conexuser = new HashSet<conexuser>();
            this.movimi = new HashSet<movimi>();
            this.movimi1 = new HashSet<movimi>();
            this.permiso = new HashSet<permiso>();
            this.usuariocia = new HashSet<usuariocia>();
        }
    
        public int idusuario { get; set; }
        public int idusuariodatos { get; set; }
        public string user { get; set; }
        public string contrasena { get; set; }
        public Nullable<System.DateTime> fechaulticonex { get; set; }
        public Nullable<System.DateTime> ultimobloqueo { get; set; }
        public int intentosfallidos { get; set; }
        public bool bloqueado { get; set; }
        public bool conectado { get; set; }
    
        public virtual ICollection<conexuser> conexuser { get; set; }
        public virtual datosusuario datosusuario { get; set; }
        public virtual ICollection<movimi> movimi { get; set; }
        public virtual ICollection<movimi> movimi1 { get; set; }
        public virtual ICollection<permiso> permiso { get; set; }
        public virtual ICollection<usuariocia> usuariocia { get; set; }
    }
    
}
