//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entities
{
    public partial class saldoscuentas
    {
        public int idsaldoscuentas { get; set; }
        public int idsucursal { get; set; }
        public int cuenta { get; set; }
        public string anio { get; set; }
        public int mes { get; set; }
        public decimal saldomes { get; set; }
        public decimal credimes { get; set; }
        public decimal debimes { get; set; }
    
        public virtual maeconta maeconta { get; set; }
        public virtual sucursal sucursal { get; set; }
    }
    
}
