//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entities
{
    public partial class maetribut
    {
        public int idtributario { get; set; }
        public string codigotrib { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> tope { get; set; }
        public Nullable<int> idnittope { get; set; }
    
        public virtual maenits maenits { get; set; }
    }
    
}
