namespace App.Forms.Cartera
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Forms;
    using Entities.Types;
    using Negocios.Cartera;

    public partial class Form_FormatoRc : Form
    {
        private FormatorcN negocioFormato;

        private string butonclick;

        private bool usrClose;

        private Funciones funtions;

        public Form_FormatoRc()
        {
            this.negocioFormato = new FormatorcN();
            this.funtions = new Funciones();
            this.InitializeComponent();
        }

        #region VISUALIZACION

        private void CamposActivos()
        {
            txt_ancho.Enabled = true;
            txt_CCiudCliente.Enabled = true;
            txt_CCiuEmpresa.Enabled = true;
            txt_CCodCliente.Enabled = true;
            txt_CCodCob.Enabled = true;
            txt_CComis.Enabled = true;
            txt_CConcRecib.Enabled = true;
            txt_CCredAsin.Enabled = true;
            txt_CCuenAsin.Enabled = true;
            txt_CDebAsin.Enabled = true;
            txt_CDirecc.Enabled = true;
            txt_CDirEmp.Enabled = true;
            txt_CDto.Enabled = true;
            txt_CDtoFact.Enabled = true;
            txt_CElabor.Enabled = true;
            txt_CEntForPago.Enabled = true;
            txt_CFechaConsig.Enabled = true;
            txt_CFechaRec.Enabled = true;
            txt_CFormaPago.Enabled = true;
            txt_CIca.Enabled = true;
            txt_CIcaFact.Enabled = true;
            txt_CIntMora.Enabled = true;
            txt_CIva50.Enabled = true;
            txt_CMenRec1.Enabled = true;
            txt_CMenRec2.Enabled = true;
            txt_CMenRec3.Enabled = true;
            txt_CMenRec4.Enabled = true;
            txt_CNit.Enabled = true;
            txt_CNitEmp.Enabled = true;
            txt_CNomCliente.Enabled = true;
            txt_CNomCob.Enabled = true;
            txt_CNomCuen.Enabled = true;
            txt_CNomEmp.Enabled = true;
            txt_CNumAprob.Enabled = true;
            txt_CNumFactu.Enabled = true;
            txt_CNumFactura.Enabled = true;
            txt_CNumFPago.Enabled = true;
            txt_CNumRecibo.Enabled = true;
            txt_CObser1.Enabled = true;
            txt_CObser2.Enabled = true;
            txt_CObser3.Enabled = true;
            txt_CObser4.Enabled = true;
            txt_CRetenFactu.Enabled = true;
            txt_CRetenIva.Enabled = true;
            txt_CSaldoCli.Enabled = true;
            txt_CTeleEmp.Enabled = true;
            txt_CTelefono.Enabled = true;
            txt_CTotFactu.Enabled = true;
            txt_CValFPago.Enabled = true;
            txt_CValorFact.Enabled = true;
            txt_CValorLetra.Enabled = true;
            txt_CValRecib.Enabled = true;
            txt_CVendCliente.Enabled = true;
            txt_FCiudCliente.Enabled = true;
            txt_FCiuEmpresa.Enabled = true;
            txt_FCodCliente.Enabled = true;
            txt_FCodCob.Enabled = true;
            txt_FComis.Enabled = true;
            txt_FConcRecib.Enabled = true;
            txt_FCredAsin.Enabled = true;
            txt_FCuenAsin.Enabled = true;
            txt_FDebAsin.Enabled = true;
            txt_FDirecc.Enabled = true;
            txt_FDirEmp.Enabled = true;
            txt_FDto.Enabled = true;
            txt_FDtoFact.Enabled = true;
            txt_FElabor.Enabled = true;
            txt_FEntForPago.Enabled = true;
            txt_FFechaConsig.Enabled = true;
            txt_FFechaRec.Enabled = true;
            txt_FFormaPago.Enabled = true;
            txt_FIca.Enabled = true;
            txt_FIcaFact.Enabled = true;
            txt_FIntMora.Enabled = true;
            txt_FIva50.Enabled = true;
            txt_FMenRec1.Enabled = true;
            txt_FMenRec2.Enabled = true;
            txt_FMenRec3.Enabled = true;
            txt_FMenRec4.Enabled = true;
            txt_FNit.Enabled = true;
            txt_FNitEmp.Enabled = true;
            txt_FNomCliente.Enabled = true;
            txt_FNomCob.Enabled = true;
            txt_FNomCuen.Enabled = true;
            txt_FNomEmp.Enabled = true;
            txt_FNumAprob.Enabled = true;
            txt_FNumFactu.Enabled = true;
            txt_FNumFactura.Enabled = true;
            txt_FNumFPago.Enabled = true;
            txt_FNumRecibo.Enabled = true;
            txt_FObser1.Enabled = true;
            txt_FObser2.Enabled = true;
            txt_FObser3.Enabled = true;
            txt_FObser4.Enabled = true;
            txt_formato.Enabled = true;
            txt_FRetenFactu.Enabled = true;
            txt_FRetenIva.Enabled = true;
            txt_FSaldoCli.Enabled = true;
            txt_FTelefono.Enabled = true;
            txt_FTelEmp.Enabled = true;
            txt_FTotFactu.Enabled = true;
            txt_FValFPago.Enabled = true;
            txt_FValorFact.Enabled = true;
            txt_FValorLetra.Enabled = true;
            txt_FValRecib.Enabled = true;
            txt_FVendCliente.Enabled = true;
            txt_lineas.Enabled = true;
            txt_nombre.Enabled = true;
            txt_PreCiudCliente.Enabled = true;
            txt_PreCiuEmpresa.Enabled = true;
            txt_PreCodCliente.Enabled = true;
            txt_PreCodCob.Enabled = true;
            txt_PreComis.Enabled = true;
            txt_PreConcRecib.Enabled = true;
            txt_PreCredAsin.Enabled = true;
            txt_PreCuenAsin.Enabled = true;
            txt_PreDebAsin.Enabled = true;
            txt_PreDirecc.Enabled = true;
            txt_PreDirEmp.Enabled = true;
            txt_PreDto.Enabled = true;
            txt_PreDtoFact.Enabled = true;
            txt_PreElabor.Enabled = true;
            txt_PreEntForPago.Enabled = true;
            txt_PreFechaConsig.Enabled = true;
            txt_PreFechaRec.Enabled = true;
            txt_PreFormaPago.Enabled = true;
            txt_PreIca.Enabled = true;
            txt_PreIcaFact.Enabled = true;
            txt_PreIntMora.Enabled = true;
            txt_PreIva50.Enabled = true;
            txt_PreMenRec1.Enabled = true;
            txt_PreMenRec2.Enabled = true;
            txt_PreMenRec3.Enabled = true;
            txt_PreMenRec4.Enabled = true;
            txt_PreNit.Enabled = true;
            txt_PreNitEmp.Enabled = true;
            txt_PreNomCob.Enabled = true;
            txt_PreNomCliente.Enabled = true;
            txt_PreNomCuen.Enabled = true;
            txt_PreNomEmp.Enabled = true;
            txt_PreNumAprob.Enabled = true;
            txt_PreNumFactu.Enabled = true;
            txt_PreNumFactura.Enabled = true;
            txt_PreNumFPago.Enabled = true;
            txt_preNumRecibo.Enabled = true;
            txt_PreObser1.Enabled = true;
            txt_PreObser2.Enabled = true;
            txt_PreObser3.Enabled = true;
            txt_PreObser4.Enabled = true;
            txt_PreRetenFactu.Enabled = true;
            txt_PreRetenIva.Enabled = true;
            txt_PreSaldoCli.Enabled = true;
            txt_PreTelefono.Enabled = true;
            txt_PreTelEmp.Enabled = true;
            txt_PreTotFactu.Enabled = true;
            txt_PreValFPago.Enabled = true;
            txt_PreValorFact.Enabled = true;
            txt_PreValorLetra.Enabled = true;
            txt_PreValRecib.Enabled = true;
            txt_PreVendCliente.Enabled = true;
            txt_TiCiudCliente.Enabled = true;
            txt_TICiuEmpresa.Enabled = true;
            txt_TiCodCliente.Enabled = true;
            txt_TiCodCob.Enabled = true;
            txt_TiComis.Enabled = true;
            txt_TiConcRecib.Enabled = true;
            txt_TiCredAsin.Enabled = true;
            txt_TiCuenAsin.Enabled = true;
            txt_TiDebAsin.Enabled = true;
            txt_TiDirecc.Enabled = true;
            txt_TiDirEmp.Enabled = true;
            txt_TiDto.Enabled = true;
            txt_TiDtoFact.Enabled = true;
            txt_TiElabor.Enabled = true;
            txt_TiEntForPago.Enabled = true;
            txt_TiFechaConsig.Enabled = true;
            txt_TiFechaRec.Enabled = true;
            txt_TiFormaPago.Enabled = true;
            txt_TiIca.Enabled = true;
            txt_TiIcaFact.Enabled = true;
            txt_TiIntMora.Enabled = true;
            txt_TiIva50.Enabled = true;
            txt_TiMenRec1.Enabled = true;
            txt_TiMenRec2.Enabled = true;
            txt_TiMenRec3.Enabled = true;
            txt_TiMenRec4.Enabled = true;
            txt_TiNit.Enabled = true;
            txt_TiNitEmp.Enabled = true;
            txt_TiNomCliente.Enabled = true;
            txt_TiNomCob.Enabled = true;
            txt_TiNomCuen.Enabled = true;
            txt_TiNomEmp.Enabled = true;
            txt_TiNumAprob.Enabled = true;
            txt_TiNumFactu.Enabled = true;
            txt_TiNumFactura.Enabled = true;
            txt_TiNumFPago.Enabled = true;
            txt_TiNumRecibo.Enabled = true;
            txt_TiObser1.Enabled = true;
            txt_TiObser2.Enabled = true;
            txt_TiObser3.Enabled = true;
            txt_TiObser4.Enabled = true;
            txt_TiRetenFactu.Enabled = true;
            txt_TiRetenIva.Enabled = true;
            txt_TiSaldoCli.Enabled = true;
            txt_TiTelefono.Enabled = true;
            txt_TiTelEmp.Enabled = true;
            txt_TiTotFactu.Enabled = true;
            txt_TiValFPago.Enabled = true;
            txt_TiValorFact.Enabled = true;
            txt_TiValorLetra.Enabled = true;
            txt_TiValRecib.Enabled = true;
            txt_TiVendCliente.Enabled = true;
            check_avanza.Enabled = true;
            check_CiudCliente.Enabled = true;
            check_CodCliente.Enabled = true;
            check_CodCob.Enabled = true;
            check_Comis.Enabled = true;
            check_ConcRecib.Enabled = true;
            check_CredAsin.Enabled = true;
            check_CuenAsin.Enabled = true;
            check_DebAsin.Enabled = true;
            check_Direcc.Enabled = true;
            check_DirEmp.Enabled = true;
            check_Dto.Enabled = true;
            check_DtoFact.Enabled = true;
            check_Elabor.Enabled = true;
            check_EntForPago.Enabled = true;
            check_FCiuEmpresa.Enabled = true;
            check_FechaConsig.Enabled = true;
            check_FechaRec.Enabled = true;
            check_FormaPago.Enabled = true;
            check_FTotFactu.Enabled = true;
            check_Ica.Enabled = true;
            check_IcaFact.Enabled = true;
            check_IntMora.Enabled = true;
            check_Iva50.Enabled = true;
            check_MenRec1.Enabled = true;
            check_MenRec2.Enabled = true;
            check_MenRec3.Enabled = true;
            check_MenRec4.Enabled = true;
            check_Nit.Enabled = true;
            check_NitEmp.Enabled = true;
            check_NomCliente.Enabled = true;
            check_NomCob.Enabled = true;
            check_NomCuen.Enabled = true;
            check_NomEmp.Enabled = true;
            check_NumAprob.Enabled = true;
            check_NumFactu.Enabled = true;
            check_NumFactura.Enabled = true;
            check_NumRecibo.Enabled = true;
            check_NumFPago.Enabled = true;
            check_NumRecibo.Enabled = true;
            check_Obser1.Enabled = true;
            check_Obser2.Enabled = true;
            check_Obser3.Enabled = true;
            check_Obser4.Enabled = true;
            check_RetenFactu.Enabled = true;
            check_RetenIva.Enabled = true;
            check_SaldoCli.Enabled = true;
            check_Telefono.Enabled = true;
            check_TelEmp.Enabled = true;
            check_ValFPago.Enabled = true;
            check_ValorFact.Enabled = true;
            check_ValorLetra.Enabled = true;
            check_ValRecib.Enabled = true;
            check_VendCliente.Enabled = true;
        }

        private void CamposInactivos()
        {
            txt_ancho.Enabled = false;
            txt_CCiudCliente.Enabled = false;
            txt_CCiuEmpresa.Enabled = false;
            txt_CCodCliente.Enabled = false;
            txt_CCodCob.Enabled = false;
            txt_CComis.Enabled = false;
            txt_CConcRecib.Enabled = false;
            txt_CCredAsin.Enabled = false;
            txt_CCuenAsin.Enabled = false;
            txt_CDebAsin.Enabled = false;
            txt_CDirecc.Enabled = false;
            txt_CDirEmp.Enabled = false;
            txt_CDto.Enabled = false;
            txt_CDtoFact.Enabled = false;
            txt_CElabor.Enabled = false;
            txt_CEntForPago.Enabled = false;
            txt_CFechaConsig.Enabled = false;
            txt_CFechaRec.Enabled = false;
            txt_CFormaPago.Enabled = false;
            txt_CIca.Enabled = false;
            txt_CIcaFact.Enabled = false;
            txt_CIntMora.Enabled = false;
            txt_CIva50.Enabled = false;
            txt_CMenRec1.Enabled = false;
            txt_CMenRec2.Enabled = false;
            txt_CMenRec3.Enabled = false;
            txt_CMenRec4.Enabled = false;
            txt_CNit.Enabled = false;
            txt_CNitEmp.Enabled = false;
            txt_CNomCliente.Enabled = false;
            txt_CNomCob.Enabled = false;
            txt_CNomCuen.Enabled = false;
            txt_CNomEmp.Enabled = false;
            txt_CNumAprob.Enabled = false;
            txt_CNumFactu.Enabled = false;
            txt_CNumFactura.Enabled = false;
            txt_CNumFPago.Enabled = false;
            txt_CNumRecibo.Enabled = false;
            txt_CObser1.Enabled = false;
            txt_CObser2.Enabled = false;
            txt_CObser3.Enabled = false;
            txt_CObser4.Enabled = false;
            txt_CRetenFactu.Enabled = false;
            txt_CRetenIva.Enabled = false;
            txt_CSaldoCli.Enabled = false;
            txt_CTeleEmp.Enabled = false;
            txt_CTelefono.Enabled = false;
            txt_CTotFactu.Enabled = false;
            txt_CValFPago.Enabled = false;
            txt_CValorFact.Enabled = false;
            txt_CValorLetra.Enabled = false;
            txt_CValRecib.Enabled = false;
            txt_CVendCliente.Enabled = false;
            txt_FCiudCliente.Enabled = false;
            txt_FCiuEmpresa.Enabled = false;
            txt_FCodCliente.Enabled = false;
            txt_FCodCob.Enabled = false;
            txt_FComis.Enabled = false;
            txt_FConcRecib.Enabled = false;
            txt_FCredAsin.Enabled = false;
            txt_FCuenAsin.Enabled = false;
            txt_FDebAsin.Enabled = false;
            txt_FDirecc.Enabled = false;
            txt_FDirEmp.Enabled = false;
            txt_FDto.Enabled = false;
            txt_FDtoFact.Enabled = false;
            txt_FElabor.Enabled = false;
            txt_FEntForPago.Enabled = false;
            txt_FFechaConsig.Enabled = false;
            txt_FFechaRec.Enabled = false;
            txt_FFormaPago.Enabled = false;
            txt_FIca.Enabled = false;
            txt_FIcaFact.Enabled = false;
            txt_FIntMora.Enabled = false;
            txt_FIva50.Enabled = false;
            txt_FMenRec1.Enabled = false;
            txt_FMenRec2.Enabled = false;
            txt_FMenRec3.Enabled = false;
            txt_FMenRec4.Enabled = false;
            txt_FNit.Enabled = false;
            txt_FNitEmp.Enabled = false;
            txt_FNomCliente.Enabled = false;
            txt_FNomCob.Enabled = false;
            txt_FNomCuen.Enabled = false;
            txt_FNomEmp.Enabled = false;
            txt_FNumAprob.Enabled = false;
            txt_FNumFactu.Enabled = false;
            txt_FNumFactura.Enabled = false;
            txt_FNumFPago.Enabled = false;
            txt_FNumRecibo.Enabled = false;
            txt_FObser1.Enabled = false;
            txt_FObser2.Enabled = false;
            txt_FObser3.Enabled = false;
            txt_FObser4.Enabled = false;
            txt_formato.Enabled = false;
            txt_FRetenFactu.Enabled = false;
            txt_FRetenIva.Enabled = false;
            txt_FSaldoCli.Enabled = false;
            txt_FTelefono.Enabled = false;
            txt_FTelEmp.Enabled = false;
            txt_FTotFactu.Enabled = false;
            txt_FValFPago.Enabled = false;
            txt_FValorFact.Enabled = false;
            txt_FValorLetra.Enabled = false;
            txt_FValRecib.Enabled = false;
            txt_FVendCliente.Enabled = false;
            txt_lineas.Enabled = false;
            txt_nombre.Enabled = false;
            txt_PreCiudCliente.Enabled = false;
            txt_PreCiuEmpresa.Enabled = false;
            txt_PreCodCliente.Enabled = false;
            txt_PreCodCob.Enabled = false;
            txt_PreComis.Enabled = false;
            txt_PreConcRecib.Enabled = false;
            txt_PreCredAsin.Enabled = false;
            txt_PreCuenAsin.Enabled = false;
            txt_PreDebAsin.Enabled = false;
            txt_PreDirecc.Enabled = false;
            txt_PreDirEmp.Enabled = false;
            txt_PreDto.Enabled = false;
            txt_PreDtoFact.Enabled = false;
            txt_PreElabor.Enabled = false;
            txt_PreEntForPago.Enabled = false;
            txt_PreFechaConsig.Enabled = false;
            txt_PreFechaRec.Enabled = false;
            txt_PreFormaPago.Enabled = false;
            txt_PreIca.Enabled = false;
            txt_PreIcaFact.Enabled = false;
            txt_PreIntMora.Enabled = false;
            txt_PreIva50.Enabled = false;
            txt_PreMenRec1.Enabled = false;
            txt_PreMenRec2.Enabled = false;
            txt_PreMenRec3.Enabled = false;
            txt_PreMenRec4.Enabled = false;
            txt_PreNit.Enabled = false;
            txt_PreNitEmp.Enabled = false;
            txt_PreNomCob.Enabled = false;
            txt_PreNomCliente.Enabled = false;
            txt_PreNomCuen.Enabled = false;
            txt_PreNomEmp.Enabled = false;
            txt_PreNumAprob.Enabled = false;
            txt_PreNumFactu.Enabled = false;
            txt_PreNumFactura.Enabled = false;
            txt_PreNumFPago.Enabled = false;
            txt_preNumRecibo.Enabled = false;
            txt_PreObser1.Enabled = false;
            txt_PreObser2.Enabled = false;
            txt_PreObser3.Enabled = false;
            txt_PreObser4.Enabled = false;
            txt_PreRetenFactu.Enabled = false;
            txt_PreRetenIva.Enabled = false;
            txt_PreSaldoCli.Enabled = false;
            txt_PreTelefono.Enabled = false;
            txt_PreTelEmp.Enabled = false;
            txt_PreTotFactu.Enabled = false;
            txt_PreValFPago.Enabled = false;
            txt_PreValorFact.Enabled = false;
            txt_PreValorLetra.Enabled = false;
            txt_PreValRecib.Enabled = false;
            txt_PreVendCliente.Enabled = false;
            txt_TiCiudCliente.Enabled = false;
            txt_TICiuEmpresa.Enabled = false;
            txt_TiCodCliente.Enabled = false;
            txt_TiCodCob.Enabled = false;
            txt_TiComis.Enabled = false;
            txt_TiConcRecib.Enabled = false;
            txt_TiCredAsin.Enabled = false;
            txt_TiCuenAsin.Enabled = false;
            txt_TiDebAsin.Enabled = false;
            txt_TiDirecc.Enabled = false;
            txt_TiDirEmp.Enabled = false;
            txt_TiDto.Enabled = false;
            txt_TiDtoFact.Enabled = false;
            txt_TiElabor.Enabled = false;
            txt_TiEntForPago.Enabled = false;
            txt_TiFechaConsig.Enabled = false;
            txt_TiFechaRec.Enabled = false;
            txt_TiFormaPago.Enabled = false;
            txt_TiIca.Enabled = false;
            txt_TiIcaFact.Enabled = false;
            txt_TiIntMora.Enabled = false;
            txt_TiIva50.Enabled = false;
            txt_TiMenRec1.Enabled = false;
            txt_TiMenRec2.Enabled = false;
            txt_TiMenRec3.Enabled = false;
            txt_TiMenRec4.Enabled = false;
            txt_TiNit.Enabled = false;
            txt_TiNitEmp.Enabled = false;
            txt_TiNomCliente.Enabled = false;
            txt_TiNomCob.Enabled = false;
            txt_TiNomCuen.Enabled = false;
            txt_TiNomEmp.Enabled = false;
            txt_TiNumAprob.Enabled = false;
            txt_TiNumFactu.Enabled = false;
            txt_TiNumFactura.Enabled = false;
            txt_TiNumFPago.Enabled = false;
            txt_TiNumRecibo.Enabled = false;
            txt_TiObser1.Enabled = false;
            txt_TiObser2.Enabled = false;
            txt_TiObser3.Enabled = false;
            txt_TiObser4.Enabled = false;
            txt_TiRetenFactu.Enabled = false;
            txt_TiRetenIva.Enabled = false;
            txt_TiSaldoCli.Enabled = false;
            txt_TiTelefono.Enabled = false;
            txt_TiTelEmp.Enabled = false;
            txt_TiTotFactu.Enabled = false;
            txt_TiValFPago.Enabled = false;
            txt_TiValorFact.Enabled = false;
            txt_TiValorLetra.Enabled = false;
            txt_TiValRecib.Enabled = false;
            txt_TiVendCliente.Enabled = false;
            check_avanza.Enabled = false;
            check_CiudCliente.Enabled = false;
            check_CodCliente.Enabled = false;
            check_CodCob.Enabled = false;
            check_Comis.Enabled = false;
            check_ConcRecib.Enabled = false;
            check_CredAsin.Enabled = false;
            check_CuenAsin.Enabled = false;
            check_DebAsin.Enabled = false;
            check_Direcc.Enabled = false;
            check_DirEmp.Enabled = false;
            check_Dto.Enabled = false;
            check_DtoFact.Enabled = false;
            check_Elabor.Enabled = false;
            check_EntForPago.Enabled = false;
            check_FCiuEmpresa.Enabled = false;
            check_FechaConsig.Enabled = false;
            check_FechaRec.Enabled = false;
            check_FormaPago.Enabled = false;
            check_FTotFactu.Enabled = false;
            check_Ica.Enabled = false;
            check_IcaFact.Enabled = false;
            check_IntMora.Enabled = false;
            check_Iva50.Enabled = false;
            check_MenRec1.Enabled = false;
            check_MenRec2.Enabled = false;
            check_MenRec3.Enabled = false;
            check_MenRec4.Enabled = false;
            check_Nit.Enabled = false;
            check_NitEmp.Enabled = false;
            check_NomCliente.Enabled = false;
            check_NomCob.Enabled = false;
            check_NomCuen.Enabled = false;
            check_NomEmp.Enabled = false;
            check_NumAprob.Enabled = false;
            check_NumFactu.Enabled = false;
            check_NumFactura.Enabled = false;
            check_NumRecibo.Enabled = false;
            check_NumFPago.Enabled = false;
            check_NumRecibo.Enabled = false;
            check_Obser1.Enabled = false;
            check_Obser2.Enabled = false;
            check_Obser3.Enabled = false;
            check_Obser4.Enabled = false;
            check_RetenFactu.Enabled = false;
            check_RetenIva.Enabled = false;
            check_SaldoCli.Enabled = false;
            check_Telefono.Enabled = false;
            check_TelEmp.Enabled = false;
            check_ValFPago.Enabled = false;
            check_ValorFact.Enabled = false;
            check_ValorLetra.Enabled = false;
            check_ValRecib.Enabled = false;
            check_VendCliente.Enabled = false;
        }

                private void CamposVacios()
        {
            txt_ancho.Text = string.Empty;
            txt_CCiudCliente.Text = string.Empty;
            txt_CCiuEmpresa.Text = string.Empty;
            txt_CCodCliente.Text = string.Empty;
            txt_CCodCob.Text = string.Empty;
            txt_CComis.Text = string.Empty;
            txt_CConcRecib.Text = string.Empty;
            txt_CCredAsin.Text = string.Empty;
            txt_CCuenAsin.Text = string.Empty;
            txt_CDebAsin.Text = string.Empty;
            txt_CDirecc.Text = string.Empty;
            txt_CDirEmp.Text = string.Empty;
            txt_CDto.Text = string.Empty;
            txt_CDtoFact.Text = string.Empty;
            txt_CElabor.Text = string.Empty;
            txt_CEntForPago.Text = string.Empty;
            txt_CFechaConsig.Text = string.Empty;
            txt_CFechaRec.Text = string.Empty;
            txt_CFormaPago.Text = string.Empty;
            txt_CIca.Text = string.Empty;
            txt_CIcaFact.Text = string.Empty;
            txt_CIntMora.Text = string.Empty;
            txt_CIva50.Text = string.Empty;
            txt_CMenRec1.Text = string.Empty;
            txt_CMenRec2.Text = string.Empty;
            txt_CMenRec3.Text = string.Empty;
            txt_CMenRec4.Text = string.Empty;
            txt_CNit.Text = string.Empty;
            txt_CNitEmp.Text = string.Empty;
            txt_CNomCliente.Text = string.Empty;
            txt_CNomCob.Text = string.Empty;
            txt_CNomCuen.Text = string.Empty;
            txt_CNomEmp.Text = string.Empty;
            txt_CNumAprob.Text = string.Empty;
            txt_CNumFactu.Text = string.Empty;
            txt_CNumFactura.Text = string.Empty;
            txt_CNumFPago.Text = string.Empty;
            txt_CNumRecibo.Text = string.Empty;
            txt_CObser1.Text = string.Empty;
            txt_CObser2.Text = string.Empty;
            txt_CObser3.Text = string.Empty;
            txt_CObser4.Text = string.Empty;
            txt_CRetenFactu.Text = string.Empty;
            txt_CRetenIva.Text = string.Empty;
            txt_CSaldoCli.Text = string.Empty;
            txt_CTeleEmp.Text = string.Empty;
            txt_CTelefono.Text = string.Empty;
            txt_CTotFactu.Text = string.Empty;
            txt_CValFPago.Text = string.Empty;
            txt_CValorFact.Text = string.Empty;
            txt_CValorLetra.Text = string.Empty;
            txt_CValRecib.Text = string.Empty;
            txt_CVendCliente.Text = string.Empty;
            txt_FCiudCliente.Text = string.Empty;
            txt_FCiuEmpresa.Text = string.Empty;
            txt_FCodCliente.Text = string.Empty;
            txt_FCodCob.Text = string.Empty;
            txt_FComis.Text = string.Empty;
            txt_FConcRecib.Text = string.Empty;
            txt_FCredAsin.Text = string.Empty;
            txt_FCuenAsin.Text = string.Empty;
            txt_FDebAsin.Text = string.Empty;
            txt_FDirecc.Text = string.Empty;
            txt_FDirEmp.Text = string.Empty;
            txt_FDto.Text = string.Empty;
            txt_FDtoFact.Text = string.Empty;
            txt_FElabor.Text = string.Empty;
            txt_FEntForPago.Text = string.Empty;
            txt_FFechaConsig.Text = string.Empty;
            txt_FFechaRec.Text = string.Empty;
            txt_FFormaPago.Text = string.Empty;
            txt_FIca.Text = string.Empty;
            txt_FIcaFact.Text = string.Empty;
            txt_FIntMora.Text = string.Empty;
            txt_FIva50.Text = string.Empty;
            txt_FMenRec1.Text = string.Empty;
            txt_FMenRec2.Text = string.Empty;
            txt_FMenRec3.Text = string.Empty;
            txt_FMenRec4.Text = string.Empty;
            txt_FNit.Text = string.Empty;
            txt_FNitEmp.Text = string.Empty;
            txt_FNomCliente.Text = string.Empty;
            txt_FNomCob.Text = string.Empty;
            txt_FNomCuen.Text = string.Empty;
            txt_FNomEmp.Text = string.Empty;
            txt_FNumAprob.Text = string.Empty;
            txt_FNumFactu.Text = string.Empty;
            txt_FNumFactura.Text = string.Empty;
            txt_FNumFPago.Text = string.Empty;
            txt_FNumRecibo.Text = string.Empty;
            txt_FObser1.Text = string.Empty;
            txt_FObser2.Text = string.Empty;
            txt_FObser3.Text = string.Empty;
            txt_FObser4.Text = string.Empty;
            txt_formato.Text = string.Empty;
            txt_FRetenFactu.Text = string.Empty;
            txt_FRetenIva.Text = string.Empty;
            txt_FSaldoCli.Text = string.Empty;
            txt_FTelefono.Text = string.Empty;
            txt_FTelEmp.Text = string.Empty;
            txt_FTotFactu.Text = string.Empty;
            txt_FValFPago.Text = string.Empty;
            txt_FValorFact.Text = string.Empty;
            txt_FValorLetra.Text = string.Empty;
            txt_FValRecib.Text = string.Empty;
            txt_FVendCliente.Text = string.Empty;
            txt_lineas.Text = string.Empty;
            txt_nombre.Text = string.Empty;
            txt_PreCiudCliente.Text = string.Empty;
            txt_PreCiuEmpresa.Text = string.Empty;
            txt_PreCodCliente.Text = string.Empty;
            txt_PreCodCob.Text = string.Empty;
            txt_PreComis.Text = string.Empty;
            txt_PreConcRecib.Text = string.Empty;
            txt_PreCredAsin.Text = string.Empty;
            txt_PreCuenAsin.Text = string.Empty;
            txt_PreDebAsin.Text = string.Empty;
            txt_PreDirecc.Text = string.Empty;
            txt_PreDirEmp.Text = string.Empty;
            txt_PreDto.Text = string.Empty;
            txt_PreDtoFact.Text = string.Empty;
            txt_PreElabor.Text = string.Empty;
            txt_PreEntForPago.Text = string.Empty;
            txt_PreFechaConsig.Text = string.Empty;
            txt_PreFechaRec.Text = string.Empty;
            txt_PreFormaPago.Text = string.Empty;
            txt_PreIca.Text = string.Empty;
            txt_PreIcaFact.Text = string.Empty;
            txt_PreIntMora.Text = string.Empty;
            txt_PreIva50.Text = string.Empty;
            txt_PreMenRec1.Text = string.Empty;
            txt_PreMenRec2.Text = string.Empty;
            txt_PreMenRec3.Text = string.Empty;
            txt_PreMenRec4.Text = string.Empty;
            txt_PreNit.Text = string.Empty;
            txt_PreNitEmp.Text = string.Empty;
            txt_PreNomCob.Text = string.Empty;
            txt_PreNomCliente.Text = string.Empty;
            txt_PreNomCuen.Text = string.Empty;
            txt_PreNomEmp.Text = string.Empty;
            txt_PreNumAprob.Text = string.Empty;
            txt_PreNumFactu.Text = string.Empty;
            txt_PreNumFactura.Text = string.Empty;
            txt_PreNumFPago.Text = string.Empty;
            txt_preNumRecibo.Text = string.Empty;
            txt_PreObser1.Text = string.Empty;
            txt_PreObser2.Text = string.Empty;
            txt_PreObser3.Text = string.Empty;
            txt_PreObser4.Text = string.Empty;
            txt_PreRetenFactu.Text = string.Empty;
            txt_PreRetenIva.Text = string.Empty;
            txt_PreSaldoCli.Text = string.Empty;
            txt_PreTelefono.Text = string.Empty;
            txt_PreTelEmp.Text = string.Empty;
            txt_PreTotFactu.Text = string.Empty;
            txt_PreValFPago.Text = string.Empty;
            txt_PreValorFact.Text = string.Empty;
            txt_PreValorLetra.Text = string.Empty;
            txt_PreValRecib.Text = string.Empty;
            txt_PreVendCliente.Text = string.Empty;
            txt_TiCiudCliente.Text = string.Empty;
            txt_TICiuEmpresa.Text = string.Empty;
            txt_TiCodCliente.Text = string.Empty;
            txt_TiCodCob.Text = string.Empty;
            txt_TiComis.Text = string.Empty;
            txt_TiConcRecib.Text = string.Empty;
            txt_TiCredAsin.Text = string.Empty;
            txt_TiCuenAsin.Text = string.Empty;
            txt_TiDebAsin.Text = string.Empty;
            txt_TiDirecc.Text = string.Empty;
            txt_TiDirEmp.Text = string.Empty;
            txt_TiDto.Text = string.Empty;
            txt_TiDtoFact.Text = string.Empty;
            txt_TiElabor.Text = string.Empty;
            txt_TiEntForPago.Text = string.Empty;
            txt_TiFechaConsig.Text = string.Empty;
            txt_TiFechaRec.Text = string.Empty;
            txt_TiFormaPago.Text = string.Empty;
            txt_TiIca.Text = string.Empty;
            txt_TiIcaFact.Text = string.Empty;
            txt_TiIntMora.Text = string.Empty;
            txt_TiIva50.Text = string.Empty;
            txt_TiMenRec1.Text = string.Empty;
            txt_TiMenRec2.Text = string.Empty;
            txt_TiMenRec3.Text = string.Empty;
            txt_TiMenRec4.Text = string.Empty;
            txt_TiNit.Text = string.Empty;
            txt_TiNitEmp.Text = string.Empty;
            txt_TiNomCliente.Text = string.Empty;
            txt_TiNomCob.Text = string.Empty;
            txt_TiNomCuen.Text = string.Empty;
            txt_TiNomEmp.Text = string.Empty;
            txt_TiNumAprob.Text = string.Empty;
            txt_TiNumFactu.Text = string.Empty;
            txt_TiNumFactura.Text = string.Empty;
            txt_TiNumFPago.Text = string.Empty;
            txt_TiNumRecibo.Text = string.Empty;
            txt_TiObser1.Text = string.Empty;
            txt_TiObser2.Text = string.Empty;
            txt_TiObser3.Text = string.Empty;
            txt_TiObser4.Text = string.Empty;
            txt_TiRetenFactu.Text = string.Empty;
            txt_TiRetenIva.Text = string.Empty;
            txt_TiSaldoCli.Text = string.Empty;
            txt_TiTelefono.Text = string.Empty;
            txt_TiTelEmp.Text = string.Empty;
            txt_TiTotFactu.Text = string.Empty;
            txt_TiValFPago.Text = string.Empty;
            txt_TiValorFact.Text = string.Empty;
            txt_TiValorLetra.Text = string.Empty;
            txt_TiValRecib.Text = string.Empty;
            txt_TiVendCliente.Text = string.Empty;
            check_avanza.Enabled = false;
            check_CiudCliente.Enabled = false;
            check_CodCliente.Enabled = false;
            check_CodCob.Enabled = false;
            check_Comis.Enabled = false;
            check_ConcRecib.Enabled = false;
            check_CredAsin.Enabled = false;
            check_CuenAsin.Enabled = false;
            check_DebAsin.Enabled = false;
            check_Direcc.Enabled = false;
            check_DirEmp.Enabled = false;
            check_Dto.Enabled = false;
            check_DtoFact.Enabled = false;
            check_Elabor.Enabled = false;
            check_EntForPago.Enabled = false;
            check_FCiuEmpresa.Enabled = false;
            check_FechaConsig.Enabled = false;
            check_FechaRec.Enabled = false;
            check_FormaPago.Enabled = false;
            check_FTotFactu.Enabled = false;
            check_Ica.Enabled = false;
            check_IcaFact.Enabled = false;
            check_IntMora.Enabled = false;
            check_Iva50.Enabled = false;
            check_MenRec1.Enabled = false;
            check_MenRec2.Enabled = false;
            check_MenRec3.Enabled = false;
            check_MenRec4.Enabled = false;
            check_Nit.Enabled = false;
            check_NitEmp.Enabled = false;
            check_NomCliente.Enabled = false;
            check_NomCob.Enabled = false;
            check_NomCuen.Enabled = false;
            check_NomEmp.Enabled = false;
            check_NumAprob.Enabled = false;
            check_NumFactu.Enabled = false;
            check_NumFactura.Enabled = false;
            check_NumRecibo.Enabled = false;
            check_NumFPago.Enabled = false;
            check_NumRecibo.Enabled = false;
            check_Obser1.Enabled = false;
            check_Obser2.Enabled = false;
            check_Obser3.Enabled = false;
            check_Obser4.Enabled = false;
            check_RetenFactu.Enabled = false;
            check_RetenIva.Enabled = false;
            check_SaldoCli.Enabled = false;
            check_Telefono.Enabled = false;
            check_TelEmp.Enabled = false;
            check_ValFPago.Enabled = false;
            check_ValorFact.Enabled = false;
            check_ValorLetra.Enabled = false;
            check_ValRecib.Enabled = false;
            check_VendCliente.Enabled = false;
        }
        #endregion

        #region BOTONES CLICK

        private void Btn_nuevo_Click(object sender, EventArgs e)
        {
            this.CamposActivos();
            btn_guardar.Enabled = true;
            this.butonclick = "agregar";
        }

        private void Btn_editar_Click(object sender, EventArgs e)
        {
            this.CamposInactivos();
            btn_ir.Visible = true;
            btn_ir.Enabled = true;
            this.butonclick = "editar";
            txt_formato.Enabled = true;
        }

        private void Btn_ir_Click(object sender, EventArgs e)
        {
            bool existe = this.negocioFormato.ExisteFormato(int.Parse(txt_formato.Text));
            if (existe)
            {
                List<FormatorcDataSource> formato = new List<FormatorcDataSource>();
                int format = int.Parse(txt_formato.Text);
                formato = this.negocioFormato.DevolverFormato(format);
                txt_ancho.Text = Convert.ToString(formato[0].Fila);
                txt_lineas.Text = Convert.ToString(formato[0].Columna);
                check_avanza.Checked = formato[0].Condensa;
                txt_nombre.Text = formato[0].Presentacion;
                txt_FNumRecibo.Text = Convert.ToString(formato[1].Fila);
                txt_CNumRecibo.Text = Convert.ToString(formato[1].Columna);
                check_NumRecibo.Checked = formato[1].Condensa;
                txt_preNumRecibo.Text = formato[1].Presentacion;
                txt_TiNumRecibo.Text = formato[1].Titulo;
                txt_FCiuEmpresa.Text = Convert.ToString(formato[2].Fila);
                txt_CCiuEmpresa.Text = Convert.ToString(formato[2].Columna);
                check_FCiuEmpresa.Checked = formato[2].Condensa;
                txt_PreCiuEmpresa.Text = formato[2].Presentacion;
                txt_TICiuEmpresa.Text = formato[2].Titulo;
                txt_FFechaRec.Text = Convert.ToString(formato[3].Fila);
                txt_CFechaRec.Text = Convert.ToString(formato[3].Columna);
                check_FechaRec.Checked = formato[3].Condensa;
                txt_PreFechaRec.Text = formato[3].Presentacion;
                txt_TiFechaRec.Text = formato[3].Titulo;
                txt_FCodCliente.Text = Convert.ToString(formato[4].Fila);
                txt_CCodCliente.Text = Convert.ToString(formato[4].Columna);
                check_CodCliente.Checked = formato[4].Condensa;
                txt_PreCodCliente.Text = formato[4].Presentacion;
                txt_TiCodCliente.Text = formato[4].Titulo;
                txt_FNomCliente.Text = Convert.ToString(formato[5].Fila);
                txt_CNomCliente.Text = Convert.ToString(formato[5].Columna);
                check_NomCliente.Checked = formato[5].Condensa;
                txt_PreNomCliente.Text = formato[5].Presentacion;
                txt_TiNomCliente.Text = formato[5].Titulo;
                txt_FNit.Text = Convert.ToString(formato[6].Fila);
                txt_CNit.Text = Convert.ToString(formato[6].Columna);
                check_Nit.Checked = formato[6].Condensa;
                txt_PreNit.Text = formato[6].Presentacion;
                txt_TiNit.Text = formato[6].Titulo;
                txt_FDirecc.Text = Convert.ToString(formato[7].Fila);
                txt_CDirecc.Text = Convert.ToString(formato[7].Columna);
                check_Direcc.Checked = formato[7].Condensa;
                txt_PreDirecc.Text = formato[7].Presentacion;
                txt_TiDirecc.Text = formato[7].Titulo;
                txt_FTelefono.Text = Convert.ToString(formato[8].Fila);
                txt_CTelefono.Text = Convert.ToString(formato[8].Columna);
                check_Telefono.Checked = formato[8].Condensa;
                txt_PreTelefono.Text = formato[8].Presentacion;
                txt_TiTelefono.Text = formato[8].Titulo;
                txt_FCiudCliente.Text = Convert.ToString(formato[9].Fila);
                txt_CCiudCliente.Text = Convert.ToString(formato[9].Columna);
                check_CiudCliente.Checked = formato[9].Condensa;
                txt_PreCiudCliente.Text = formato[9].Presentacion;
                txt_TiCiudCliente.Text = formato[9].Titulo;
                txt_FVendCliente.Text = Convert.ToString(formato[10].Fila);
                txt_CVendCliente.Text = Convert.ToString(formato[10].Columna);
                check_VendCliente.Checked = formato[10].Condensa;
                txt_PreVendCliente.Text = formato[10].Presentacion;
                txt_TiVendCliente.Text = formato[10].Titulo;
                txt_FValorFact.Text = Convert.ToString(formato[11].Fila);
                txt_CValorFact.Text = Convert.ToString(formato[11].Columna);
                check_ValorFact.Checked = formato[11].Condensa;
                txt_PreValorFact.Text = formato[11].Presentacion;
                txt_TiValorFact.Text = formato[11].Titulo;
                txt_FNumFactura.Text = Convert.ToString(formato[12].Fila);
                txt_CNumFactura.Text = Convert.ToString(formato[12].Columna);
                check_NumFactura.Checked = formato[12].Condensa;
                txt_PreNumFactura.Text = formato[12].Presentacion;
                txt_TiNumFactura.Text = formato[12].Titulo;
                txt_FIcaFact.Text = Convert.ToString(formato[13].Fila);
                txt_CIcaFact.Text = Convert.ToString(formato[13].Columna);
                check_IcaFact.Checked = formato[13].Condensa;
                txt_PreIcaFact.Text = formato[13].Presentacion;
                txt_TiIcaFact.Text = formato[13].Titulo;
                txt_FIva50.Text = Convert.ToString(formato[14].Fila);
                txt_CIva50.Text = Convert.ToString(formato[14].Columna);
                check_Iva50.Checked = formato[14].Condensa;
                txt_PreIva50.Text = formato[14].Presentacion;
                txt_TiIva50.Text = formato[14].Titulo;
                txt_FDtoFact.Text = Convert.ToString(formato[15].Fila);
                txt_CDtoFact.Text = Convert.ToString(formato[15].Columna);
                check_DtoFact.Checked = formato[15].Condensa;
                txt_PreDtoFact.Text = formato[15].Presentacion;
                txt_TiDtoFact.Text = formato[15].Titulo;
                txt_FRetenFactu.Text = Convert.ToString(formato[16].Fila);
                txt_CRetenFactu.Text = Convert.ToString(formato[16].Columna);
                check_RetenFactu.Checked = formato[16].Condensa;
                txt_PreRetenFactu.Text = formato[16].Presentacion;
                txt_TiRetenFactu.Text = formato[16].Titulo;
                txt_FNumFactu.Text = Convert.ToString(formato[17].Fila);
                txt_CNumFactu.Text = Convert.ToString(formato[17].Columna);
                check_NumFactu.Checked = formato[17].Condensa;
                txt_PreNumFactu.Text = formato[17].Presentacion;
                txt_TiNumFactu.Text = formato[17].Titulo;
                txt_FTotFactu.Text = Convert.ToString(formato[18].Fila);
                txt_CTotFactu.Text = Convert.ToString(formato[18].Columna);
                check_FTotFactu.Checked = formato[18].Condensa;
                txt_PreTotFactu.Text = formato[18].Presentacion;
                txt_TiTotFactu.Text = formato[18].Titulo;
                txt_FValRecib.Text = Convert.ToString(formato[19].Fila);
                txt_CValRecib.Text = Convert.ToString(formato[19].Columna);
                check_ValRecib.Checked = formato[19].Condensa;
                txt_PreValRecib.Text = formato[19].Presentacion;
                txt_TiValRecib.Text = formato[19].Titulo;
                txt_FSaldoCli.Text = Convert.ToString(formato[20].Fila);
                txt_CSaldoCli.Text = Convert.ToString(formato[20].Columna);
                check_SaldoCli.Checked = formato[20].Condensa;
                txt_PreSaldoCli.Text = formato[20].Presentacion;
                txt_TiSaldoCli.Text = formato[20].Titulo;
                txt_FIntMora.Text = Convert.ToString(formato[21].Fila);
                txt_CIntMora.Text = Convert.ToString(formato[21].Columna);
                check_IntMora.Checked = formato[21].Condensa;
                txt_PreIntMora.Text = formato[21].Presentacion;
                txt_TiIntMora.Text = formato[21].Titulo;
                txt_FComis.Text = Convert.ToString(formato[22].Fila);
                txt_CComis.Text = Convert.ToString(formato[22].Columna) ;
                check_Comis.Checked = formato[22].Condensa;
                txt_PreComis.Text = formato[22].Presentacion;
                txt_TiComis.Text = formato[22].Titulo;
                txt_FIca.Text = Convert.ToString(formato[23].Fila);
                txt_CIca.Text = Convert.ToString(formato[23].Columna);
                check_Ica.Checked = formato[23].Condensa;
                txt_PreIca.Text = formato[23].Presentacion;
                txt_TiIca.Text = formato[23].Titulo;
                txt_FDto.Text = Convert.ToString(formato[24].Fila);
                txt_CDto.Text = Convert.ToString(formato[24].Columna);
                check_Dto.Checked = formato[24].Condensa;
                txt_PreDto.Text = formato[24].Presentacion;
                txt_TiDto.Text = formato[24].Titulo;
                txt_FRetenIva.Text = Convert.ToString(formato[25].Fila);
                txt_CRetenIva.Text = Convert.ToString(formato[25].Columna);
                check_RetenIva.Checked = formato[25].Condensa;
                txt_PreRetenIva.Text = formato[25].Presentacion;
                txt_TiRetenIva.Text = formato[25].Titulo;
                txt_FConcRecib.Text =Convert.ToString(formato[26].Fila);
                txt_CConcRecib.Text = Convert.ToString(formato[26].Columna);
                check_ConcRecib.Checked = formato[26].Condensa;
                txt_PreConcRecib.Text = formato[26].Presentacion;
                txt_TiConcRecib.Text = formato[26].Titulo;
                txt_FValorLetra.Text = Convert.ToString(formato[27].Fila);
                txt_CValorLetra.Text = Convert.ToString(formato[27].Columna);
                check_ValorLetra.Checked = formato[27].Condensa;
                txt_PreValorLetra.Text = formato[27].Presentacion;
                txt_TiValorLetra.Text = formato[27].Titulo;
                txt_FFormaPago.Text = Convert.ToString(formato[28].Fila);
                txt_CFormaPago.Text = Convert.ToString(formato[28].Columna);
                check_FormaPago.Checked = formato[28].Condensa;
                txt_PreFormaPago.Text = formato[28].Presentacion;
                txt_TiFormaPago.Text = formato[28].Titulo;
                txt_FNumAprob.Text = Convert.ToString(formato[29].Fila);
                txt_CNumAprob.Text = Convert.ToString(formato[29].Columna);
                check_NumAprob.Checked = formato[29].Condensa;
                txt_PreNumAprob.Text = formato[29].Presentacion;
                txt_TiNumAprob.Text = formato[29].Titulo;
                txt_FValFPago.Text = Convert.ToString(formato[30].Fila);
                txt_CValFPago.Text = Convert.ToString(formato[30].Columna);
                check_ValFPago.Checked = formato[30].Condensa;
                txt_PreValFPago.Text = formato[30].Presentacion;
                txt_TiValFPago.Text = formato[30].Titulo;
                txt_FEntForPago.Text = Convert.ToString(formato[31].Fila);
                txt_CEntForPago.Text = Convert.ToString(formato[31].Columna);
                check_EntForPago.Checked = formato[31].Condensa;
                txt_PreEntForPago.Text = formato[31].Presentacion;
                txt_TiEntForPago.Text = formato[31].Titulo;
                txt_FNumFPago.Text = Convert.ToString(formato[32].Fila);
                txt_CNumFPago.Text = Convert.ToString(formato[32].Columna);
                check_NumFPago.Checked = formato[32].Condensa;
                txt_PreNumFPago.Text = formato[32].Presentacion;
                txt_TiNumFPago.Text = formato[32].Titulo;
                txt_FFechaConsig.Text = Convert.ToString(formato[33].Fila);
                txt_CFechaConsig.Text = Convert.ToString(formato[33].Columna);
                check_FechaConsig.Checked = formato[33].Condensa;
                txt_PreFechaConsig.Text = formato[33].Presentacion;
                txt_TiFechaConsig.Text = formato[33].Titulo;
                txt_FCuenAsin.Text = Convert.ToString(formato[34].Fila);
                txt_CCuenAsin.Text = Convert.ToString(formato[34].Columna);
                check_CuenAsin.Checked = formato[34].Condensa;
                txt_PreCuenAsin.Text = formato[34].Presentacion;
                txt_TiCuenAsin.Text = formato[34].Titulo;
                txt_FNomCuen.Text = Convert.ToString(formato[35].Fila);
                txt_CNomCuen.Text = Convert.ToString(formato[35].Columna);
                check_NomCuen.Checked = formato[35].Condensa;
                txt_PreNomCuen.Text = formato[35].Presentacion;
                txt_TiNomCuen.Text = formato[35].Titulo;
                txt_FDebAsin.Text = Convert.ToString(formato[36].Fila);
                txt_CDebAsin.Text = Convert.ToString(formato[36].Columna);
                check_DebAsin.Checked = formato[36].Condensa;
                txt_PreDebAsin.Text = formato[36].Presentacion;
                txt_TiDebAsin.Text = formato[36].Titulo;
                txt_FCredAsin.Text = Convert.ToString(formato[37].Fila);
                txt_CCredAsin.Text = Convert.ToString(formato[37].Columna);
                check_CredAsin.Checked = formato[37].Condensa;
                txt_PreCredAsin.Text = formato[37].Presentacion;
                txt_TiCredAsin.Text = formato[37].Titulo;
                txt_FNomEmp.Text = Convert.ToString(formato[38].Fila);
                txt_CNomEmp.Text = Convert.ToString(formato[38].Columna);
                check_NomEmp.Checked = formato[38].Condensa;
                txt_PreNomEmp.Text = formato[38].Presentacion;
                txt_TiNomEmp.Text = formato[38].Titulo;
                txt_FNitEmp.Text = Convert.ToString(formato[39].Fila);
                txt_CNitEmp.Text = Convert.ToString(formato[39].Columna);
                check_NitEmp.Checked = formato[39].Condensa;
                txt_PreNitEmp.Text = formato[39].Presentacion;
                txt_TiNitEmp.Text = formato[39].Titulo;
                txt_FDirEmp.Text = Convert.ToString(formato[40].Fila);
                txt_CDirEmp.Text = Convert.ToString(formato[40].Columna);
                check_DirEmp.Checked = formato[40].Condensa;
                txt_PreDirEmp.Text = formato[40].Presentacion;
                txt_TiDirEmp.Text = formato[40].Titulo;
                txt_FTelEmp.Text = Convert.ToString(formato[41].Fila);
                txt_CTeleEmp.Text = Convert.ToString(formato[41].Columna);
                check_TelEmp.Checked = formato[41].Condensa;
                txt_PreTelEmp.Text = formato[41].Presentacion;
                txt_TiTelEmp.Text = formato[41].Titulo;
                txt_FElabor.Text = Convert.ToString(formato[42].Fila);
                txt_CElabor.Text = Convert.ToString(formato[42].Columna);
                check_Elabor.Checked = formato[42].Condensa;
                txt_PreElabor.Text = formato[42].Presentacion;
                txt_TiElabor.Text = formato[42].Titulo;
                txt_FObser1.Text = Convert.ToString(formato[43].Fila);
                txt_CObser1.Text = Convert.ToString(formato[43].Columna);
                check_Obser1.Checked = formato[43].Condensa;
                txt_PreObser1.Text = formato[43].Presentacion;
                txt_TiObser1.Text = formato[43].Titulo;
                txt_FObser2.Text = Convert.ToString(formato[44].Fila);
                txt_CObser2.Text = Convert.ToString(formato[44].Columna);
                check_Obser2.Checked = formato[44].Condensa;
                txt_PreObser2.Text = formato[44].Presentacion;
                txt_TiObser2.Text = formato[44].Titulo;
                txt_FObser3.Text = Convert.ToString(formato[45].Fila);
                txt_CObser3.Text = Convert.ToString(formato[45].Columna);
                check_Obser3.Checked = formato[45].Condensa;
                txt_PreObser3.Text = formato[45].Presentacion;
                txt_TiObser3.Text = formato[45].Titulo;
                txt_FObser4.Text = Convert.ToString(formato[46].Fila);
                txt_CObser4.Text = Convert.ToString(formato[46].Columna);
                check_Obser4.Checked = formato[46].Condensa;
                txt_PreObser4.Text = formato[46].Presentacion;
                txt_TiObser4.Text = formato[46].Titulo;
                txt_FCodCob.Text = Convert.ToString(formato[47].Fila);
                txt_CCodCob.Text = Convert.ToString(formato[47].Columna);
                check_CodCob.Checked = formato[47].Condensa;
                txt_PreCodCob.Text = formato[47].Presentacion;
                txt_TiCodCob.Text = formato[47].Titulo;
                txt_FNomCob.Text = Convert.ToString(formato[48].Fila);
                txt_CNomCob.Text = Convert.ToString(formato[48].Columna);
                check_NomCob.Checked = formato[48].Condensa;
                txt_PreNomCob.Text = formato[48].Presentacion;
                txt_TiNomCob.Text = formato[48].Titulo;
                txt_FMenRec1.Text = Convert.ToString(formato[49].Fila);
                txt_CMenRec1.Text = Convert.ToString(formato[49].Columna);
                check_MenRec1.Checked = formato[49].Condensa;
                txt_PreMenRec1.Text = formato[49].Presentacion;
                txt_TiMenRec1.Text = formato[49].Titulo;
                txt_FMenRec2.Text = Convert.ToString(formato[50].Fila);
                txt_CMenRec2.Text = Convert.ToString(formato[50].Columna);
                check_MenRec2.Checked = formato[50].Condensa;
                txt_PreMenRec2.Text = formato[50].Presentacion;
                txt_TiMenRec2.Text = formato[50].Titulo;
                txt_FMenRec3.Text = Convert.ToString(formato[51].Fila);
                txt_CMenRec3.Text = Convert.ToString(formato[51].Columna);
                check_MenRec3.Checked = formato[51].Condensa;
                txt_PreMenRec3.Text = formato[51].Presentacion;
                txt_TiMenRec3.Text = formato[51].Titulo;
                txt_FMenRec4.Text = Convert.ToString(formato[52].Fila);
                txt_CMenRec4.Text = Convert.ToString(formato[52].Columna);
                check_MenRec4.Checked = formato[52].Condensa;
                txt_PreMenRec4.Text = formato[52].Presentacion;
                txt_TiMenRec4.Text = formato[52].Titulo;
                this.CamposActivos();
                btn_guardar.Enabled = true;
                txt_formato.Enabled = false;
                btn_ir.Enabled = false;
            }
            else
            {
                MessageBox.Show("El formato no existe", "ERROR", MessageBoxButtons.OK);
            }
        }

        #endregion

        #region GUARDAR DATOS

        private void Btn_guardar_Click(object sender, EventArgs e)
        {
            if (!txt_formato.Text.Equals(string.Empty) && !txt_nombre.Text.Equals(string.Empty) &&
                !txt_ancho.Text.Equals(string.Empty) && !txt_lineas.Text.Equals(string.Empty))
            {
                List<FormatorcDataSource> formato = new List<FormatorcDataSource>();
                formato = this.GuardarDatos();

                if (this.butonclick.Equals("agregar"))
                {
                    bool existe = this.negocioFormato.ExisteFormato(int.Parse(txt_formato.Text));
                    if (!existe)
                    {
                        bool guardo = this.negocioFormato.GuardoFormato(formato);
                        if (guardo)
                        {
                            MessageBox.Show("El concepto ha sido guardado", "GUARDAR", MessageBoxButtons.OK);
                            this.CamposInactivos();
                            this.CamposVacios();
                        }
                    }
                    else
                    {
                        MessageBox.Show("El formato ya existe", "ERROR", MessageBoxButtons.OK);
                    }
                }

                if (this.butonclick.Equals("editar"))
                {
                    bool guardo = this.negocioFormato.ActualizoFormato(formato);
                    if (guardo)
                    {
                        MessageBox.Show("El concepto ha sido actualizado", "GUARDAR", MessageBoxButtons.OK);
                        this.CamposInactivos();
                        this.CamposVacios();
                    }
                }
            }
            else
            {
                MessageBox.Show("Debe ingresar todos los datos", "ERROR", MessageBoxButtons.OK);
            }
        }

        private List<FormatorcDataSource> GuardarDatos()
        {
            List<string> format = new List<string>();
            format.Add("numrecibo");
            format.Add(txt_FNumRecibo.Text);
            format.Add(txt_CNumRecibo.Text);
            format.Add(check_NumRecibo.Checked == true ? "t" : "f");
            format.Add(txt_preNumRecibo.Text);
            format.Add(txt_TiNumRecibo.Text);
            format.Add("ciudempresa");
            format.Add(txt_FCiuEmpresa.Text);
            format.Add(txt_CCiuEmpresa.Text);
            format.Add(check_FCiuEmpresa.Checked == true ? "t" : "f");
            format.Add(txt_PreCiuEmpresa.Text);
            format.Add(txt_TICiuEmpresa.Text);
            format.Add("fecharecib");
            format.Add(txt_FFechaRec.Text);
            format.Add(txt_CFechaRec.Text);
            format.Add(check_FechaRec.Checked == true ? "t" : "f");
            format.Add(txt_PreFechaRec.Text);
            format.Add(txt_TiFechaRec.Text);
            format.Add("codcliente");
            format.Add(txt_FCodCliente.Text);
            format.Add(txt_CCodCliente.Text);
            format.Add(check_CodCliente.Checked == true ? "t" : "f");
            format.Add(txt_PreCodCliente.Text);
            format.Add(txt_TiCodCliente.Text);
            format.Add("nomcliente");
            format.Add(txt_FNomCliente.Text);
            format.Add(txt_CNomCliente.Text);
            format.Add(check_NomCliente.Checked == true ? "t" : "f");
            format.Add(txt_PreNomCliente.Text);
            format.Add(txt_TiNomCliente.Text);
            format.Add("nit");
            format.Add(txt_FNit.Text);
            format.Add(txt_CNit.Text);
            format.Add(check_Nit.Checked == true ? "t" : "f");
            format.Add(txt_PreNit.Text);
            format.Add(txt_TiNit.Text);
            format.Add("direccion");
            format.Add(txt_FDirecc.Text);
            format.Add(txt_CDirecc.Text);
            format.Add(check_Direcc.Checked == true ? "t" : "f");
            format.Add(txt_PreDirecc.Text);
            format.Add(txt_TiDirecc.Text);
            format.Add("telefono");
            format.Add(txt_FTelefono.Text);
            format.Add(txt_CTelefono.Text);
            format.Add(check_Telefono.Checked == true ? "t" : "f");
            format.Add(txt_PreTelefono.Text);
            format.Add(txt_TiTelefono.Text);
            format.Add("ciudcliente");
            format.Add(txt_FCiudCliente.Text);
            format.Add(txt_CCiudCliente.Text);
            format.Add(check_CiudCliente.Checked == true ? "t" : "f");
            format.Add(txt_PreCiudCliente.Text);
            format.Add(txt_TiCiudCliente.Text);
            format.Add("vendcliente");
            format.Add(txt_FVendCliente.Text);
            format.Add(txt_CVendCliente.Text);
            format.Add(check_VendCliente.Checked == true ? "t" : "f");
            format.Add(txt_PreVendCliente.Text);
            format.Add(txt_TiVendCliente.Text);
            format.Add("valorfact");
            format.Add(txt_FValorFact.Text);
            format.Add(txt_CValorFact.Text);
            format.Add(check_ValorFact.Checked == true ? "t" : "f");
            format.Add(txt_PreValorFact.Text);
            format.Add(txt_TiValorFact.Text);
            format.Add("numerofactura");
            format.Add(txt_FNumFactura.Text);
            format.Add(txt_CNumFactura.Text);
            format.Add(check_NumFactura.Checked == true ? "t" : "f");
            format.Add(txt_PreNumFactura.Text);
            format.Add(txt_TiNumFactura.Text);
            format.Add("icafactura");
            format.Add(txt_FIcaFact.Text);
            format.Add(txt_CIcaFact.Text);
            format.Add(check_IcaFact.Checked == true ? "t" : "f");
            format.Add(txt_PreIcaFact.Text);
            format.Add(txt_TiIcaFact.Text);
            format.Add("iva50");
            format.Add(txt_FIva50.Text);
            format.Add(txt_CIva50.Text);
            format.Add(check_Iva50.Checked == true ? "t" : "f");
            format.Add(txt_PreIva50.Text);
            format.Add(txt_TiIva50.Text);
            format.Add("dtofactura");
            format.Add(txt_FDtoFact.Text);
            format.Add(txt_CDtoFact.Text);
            format.Add(check_DtoFact.Checked == true ? "t" : "f");
            format.Add(txt_PreDtoFact.Text);
            format.Add(txt_TiDtoFact.Text);
            format.Add("retenfactura");
            format.Add(txt_FRetenFactu.Text);
            format.Add(txt_CRetenFactu.Text);
            format.Add(check_RetenFactu.Checked == true ? "t" : "f");
            format.Add(txt_PreRetenFactu.Text);
            format.Add(txt_TiRetenFactu.Text);
            format.Add("numerosfactura");
            format.Add(txt_FNumFactu.Text);
            format.Add(txt_CNumFactu.Text);
            format.Add(check_NumFactu.Checked == true ? "t" : "f");
            format.Add(txt_PreNumFactu.Text);
            format.Add(txt_TiNumFactu.Text);
            format.Add("totalfactura");
            format.Add(txt_FTotFactu.Text);
            format.Add(txt_CTotFactu.Text);
            format.Add(check_FTotFactu.Checked == true ? "t" : "f");
            format.Add(txt_PreTotFactu.Text);
            format.Add(txt_TiTotFactu.Text);
            format.Add("valorecibo");
            format.Add(txt_FValRecib.Text);
            format.Add(txt_CValRecib.Text);
            format.Add(check_ValRecib.Checked == true ? "t" : "f");
            format.Add(txt_PreValRecib.Text);
            format.Add(txt_TiValRecib.Text);
            format.Add("saldocliente");
            format.Add(txt_FSaldoCli.Text);
            format.Add(txt_CSaldoCli.Text);
            format.Add(check_SaldoCli.Checked == true ? "t" : "f");
            format.Add(txt_PreSaldoCli.Text);
            format.Add(txt_TiSaldoCli.Text);
            format.Add("interesmora");
            format.Add(txt_FIntMora.Text);
            format.Add(txt_CIntMora.Text);
            format.Add(check_IntMora.Checked == true ? "t" : "f");
            format.Add(txt_PreIntMora.Text);
            format.Add(txt_TiIntMora.Text);
            format.Add("comisiones");
            format.Add(txt_FComis.Text);
            format.Add(txt_CComis.Text);
            format.Add(check_Comis.Checked == true ? "t" : "f");
            format.Add(txt_PreComis.Text);
            format.Add(txt_TiComis.Text);
            format.Add("ica");
            format.Add(txt_FIca.Text);
            format.Add(txt_CIca.Text);
            format.Add(check_Ica.Checked == true ? "t" : "f");
            format.Add(txt_PreIca.Text);
            format.Add(txt_TiIca.Text);
            format.Add("descuento");
            format.Add(txt_FDto.Text);
            format.Add(txt_CDto.Text);
            format.Add(check_Dto.Checked == true ? "t" : "f");
            format.Add(txt_PreDto.Text);
            format.Add(txt_TiDto.Text);
            format.Add("retencioniva");
            format.Add(txt_FRetenIva.Text);
            format.Add(txt_CRetenIva.Text);
            format.Add(check_RetenIva.Checked == true ? "t" : "f");
            format.Add(txt_PreRetenIva.Text);
            format.Add(txt_TiRetenIva.Text);
            format.Add("conceprecibo");
            format.Add(txt_FConcRecib.Text);
            format.Add(txt_CConcRecib.Text);
            format.Add(check_ConcRecib.Checked == true ? "t" : "f");
            format.Add(txt_PreConcRecib.Text);
            format.Add(txt_TiConcRecib.Text);
            format.Add("valorletras");
            format.Add(txt_FValorLetra.Text);
            format.Add(txt_CValorLetra.Text);
            format.Add(check_ValorLetra.Checked == true ? "t" : "f");
            format.Add(txt_PreValorLetra.Text);
            format.Add(txt_TiValorLetra.Text);
            format.Add("formapago");
            format.Add(txt_FFormaPago.Text);
            format.Add(txt_CFormaPago.Text);
            format.Add(check_FormaPago.Checked == true ? "t" : "f");
            format.Add(txt_PreFormaPago.Text);
            format.Add(txt_TiFormaPago.Text);
            format.Add("numaprobacion");
            format.Add(txt_FNumAprob.Text);
            format.Add(txt_CNumAprob.Text);
            format.Add(check_NumAprob.Checked == true ? "t" : "f");
            format.Add(txt_PreNumAprob.Text);
            format.Add(txt_TiNumAprob.Text);
            format.Add("valorformapago");
            format.Add(txt_FValFPago.Text);
            format.Add(txt_CValFPago.Text);
            format.Add(check_ValFPago.Checked == true ? "t" : "f");
            format.Add(txt_PreValFPago.Text);
            format.Add(txt_TiValFPago.Text);
            format.Add("entiformapago");
            format.Add(txt_FEntForPago.Text);
            format.Add(txt_CEntForPago.Text);
            format.Add(check_EntForPago.Checked == true ? "t" : "f");
            format.Add(txt_PreEntForPago.Text);
            format.Add(txt_TiEntForPago.Text);
            format.Add("numformapago");
            format.Add(txt_FNumFPago.Text);
            format.Add(txt_CNumFPago.Text);
            format.Add(check_NumFPago.Checked == true ? "t" : "f");
            format.Add(txt_PreNumFPago.Text);
            format.Add(txt_TiNumFPago.Text);
            format.Add("fechaconsig");
            format.Add(txt_FFechaConsig.Text);
            format.Add(txt_CFechaConsig.Text);
            format.Add(check_FechaConsig.Checked == true ? "t" : "f");
            format.Add(txt_PreFechaConsig.Text);
            format.Add(txt_TiFechaConsig.Text);
            format.Add("cuentasiento");
            format.Add(txt_FCuenAsin.Text);
            format.Add(txt_CCuenAsin.Text);
            format.Add(check_CuenAsin.Checked == true ? "t" : "f");
            format.Add(txt_PreCuenAsin.Text);
            format.Add(txt_TiCuenAsin.Text);
            format.Add("nomcuenta");
            format.Add(txt_FNomCuen.Text);
            format.Add(txt_CNomCuen.Text);
            format.Add(check_NomCuen.Checked == true ? "t" : "f");
            format.Add(txt_PreNomCuen.Text);
            format.Add(txt_TiNomCuen.Text);
            format.Add("debasiento");
            format.Add(txt_FDebAsin.Text);
            format.Add(txt_CDebAsin.Text);
            format.Add(check_DebAsin.Checked == true ? "t" : "f");
            format.Add(txt_PreDebAsin.Text);
            format.Add(txt_TiDebAsin.Text);
            format.Add("credasiento");
            format.Add(txt_FCredAsin.Text);
            format.Add(txt_CCredAsin.Text);
            format.Add(check_CredAsin.Checked == true ? "t" : "f");
            format.Add(txt_PreCredAsin.Text);
            format.Add(txt_TiCredAsin.Text);
            format.Add("nomempresa");
            format.Add(txt_FNomEmp.Text);
            format.Add(txt_CNomEmp.Text);
            format.Add(check_NomEmp.Checked == true ? "t" : "f");
            format.Add(txt_PreNomEmp.Text);
            format.Add(txt_TiNomEmp.Text);
            format.Add("nitempresa");
            format.Add(txt_FNitEmp.Text);
            format.Add(txt_CNitEmp.Text);
            format.Add(check_NitEmp.Checked == true ? "t" : "f");
            format.Add(txt_PreNitEmp.Text);
            format.Add(txt_TiNitEmp.Text);
            format.Add("dirempresa");
            format.Add(txt_FDirEmp.Text);
            format.Add(txt_CDirEmp.Text);
            format.Add(check_DirEmp.Checked == true ? "t" : "f");
            format.Add(txt_PreDirEmp.Text);
            format.Add(txt_TiDirEmp.Text);
            format.Add("telempresa");
            format.Add(txt_FTelEmp.Text);
            format.Add(txt_CTeleEmp.Text);
            format.Add(check_TelEmp.Checked == true ? "t" : "f");
            format.Add(txt_PreTelEmp.Text);
            format.Add(txt_TiTelEmp.Text);
            format.Add("elaborado");
            format.Add(txt_FElabor.Text);
            format.Add(txt_CElabor.Text);
            format.Add(check_Elabor.Checked == true ? "t" : "f");
            format.Add(txt_PreElabor.Text);
            format.Add(txt_TiElabor.Text);
            format.Add("observ1");
            format.Add(txt_FObser1.Text);
            format.Add(txt_CObser1.Text);
            format.Add(check_Obser1.Checked == true ? "t" : "f");
            format.Add(txt_PreObser1.Text);
            format.Add(txt_TiObser1.Text);
            format.Add("obser2");
            format.Add(txt_FObser2.Text);
            format.Add(txt_CObser2.Text);
            format.Add(check_Obser2.Checked == true ? "t" : "f");
            format.Add(txt_PreObser2.Text);
            format.Add(txt_TiObser2.Text);
            format.Add("observ3");
            format.Add(txt_FObser3.Text);
            format.Add(txt_CObser3.Text);
            format.Add(check_Obser3.Checked == true ? "t" : "f");
            format.Add(txt_PreObser3.Text);
            format.Add(txt_TiObser3.Text);
            format.Add("observ4");
            format.Add(txt_FObser4.Text);
            format.Add(txt_CObser4.Text);
            format.Add(check_Obser4.Checked == true ? "t" : "f");
            format.Add(txt_PreObser4.Text);
            format.Add(txt_TiObser4.Text);
            format.Add("codcobrador");
            format.Add(txt_FCodCob.Text);
            format.Add(txt_CCodCob.Text);
            format.Add(check_CodCob.Checked == true ? "t" : "f");
            format.Add(txt_PreCodCob.Text);
            format.Add(txt_TiCodCob.Text);
            format.Add("nomcobrador");
            format.Add(txt_FNomCob.Text);
            format.Add(txt_CNomCob.Text);
            format.Add(check_NomCob.Checked == true ? "t" : "f");
            format.Add(txt_PreNomCob.Text);
            format.Add(txt_TiNomCob.Text);
            format.Add("mensaje1");
            format.Add(txt_FMenRec1.Text);
            format.Add(txt_CMenRec1.Text);
            format.Add(check_MenRec1.Checked == true ? "t" : "f");
            format.Add(txt_PreMenRec1.Text);
            format.Add(txt_TiMenRec1.Text);
            format.Add("mesaje2");
            format.Add(txt_FMenRec2.Text);
            format.Add(txt_CMenRec2.Text);
            format.Add(check_MenRec2.Checked == true ? "t" : "f");
            format.Add(txt_PreMenRec2.Text);
            format.Add(txt_TiMenRec2.Text);
            format.Add("mesaje3");
            format.Add(txt_FMenRec3.Text);
            format.Add(txt_CMenRec3.Text);
            format.Add(check_MenRec3.Checked == true ? "t" : "f");
            format.Add(txt_PreMenRec3.Text);
            format.Add(txt_TiMenRec3.Text);
            format.Add("mensaje4");
            format.Add(txt_FMenRec4.Text);
            format.Add(txt_CMenRec4.Text);
            format.Add(check_MenRec4.Checked == true ? "t" : "f");
            format.Add(txt_PreMenRec4.Text);
            format.Add(txt_TiMenRec4.Text);
            List<FormatorcDataSource> formato = new List<FormatorcDataSource>();
            FormatorcDataSource forini = new FormatorcDataSource();
            forini.CodigoFormato = int.Parse(txt_formato.Text);
            forini.NombreFormato = "detallefor";
            forini.Fila = int.Parse(txt_ancho.Text);
            forini.Columna = int.Parse(txt_lineas.Text);
            forini.Condensa = check_avanza.Checked;
            forini.Presentacion = txt_nombre.Text;
            forini.Titulo = txt_nombre.Text;
            formato.Add(forini);
            int i = 0;
            while (i < 312)
            {
                FormatorcDataSource forma = new FormatorcDataSource();
                forma.CodigoFormato = int.Parse(txt_formato.Text);
                forma.NombreFormato = format[i];
                forma.Fila = int.Parse(format[i + 1]);
                forma.Columna = int.Parse(format[i + 2]);
                forma.Condensa = format[i + 3] == "t" ? true : false;
                forma.Presentacion = format[i + 4];
                forma.Titulo = format[i + 5];
                i = i + 6;
                formato.Add(forma);
            }

            return formato;
        }

        #endregion

        #region VALIDACIONES

        private void EnterVal_KeyPress(object sender, KeyPressEventArgs e)
        {
            if (e.KeyChar == (char)Keys.Enter)
            {
                e.Handled = true;
                SendKeys.Send("{TAB}");
            }
            else
            {
                e.Handled = this.funtions.ValidacionNumerico(e).Handled;
            }
        }

        private void EnterTab_KeyPress(object sender, KeyPressEventArgs e)
        {
            if (e.KeyChar == (char)Keys.Enter)
            {
                e.Handled = true;
                SendKeys.Send("{TAB}");
            }
        }

        private void EnterValfor_KeyPress(object sender, KeyPressEventArgs e)
        {
            if (e.KeyChar == (char)Keys.Enter)
            {
                if (this.butonclick.Equals("agregar"))
                {
                    e.Handled = true;
                    SendKeys.Send("{TAB}");
                }
                else if (this.butonclick.Equals("editar"))
                {
                    e.Handled = true;
                    EventArgs eve = new EventArgs();
                    this.Btn_ir_Click(sender, eve);
                }
            }
            else
            {
                e.Handled = this.funtions.ValidacionNumerico(e).Handled;
            }
        }

        #endregion
              
        #region SALIR FORMULARIO

        private void Form_FormatoRc_FormClosing(object sender, FormClosingEventArgs e)
        {
            if (!this.usrClose)
            {
                DialogResult result = MessageBox.Show("Esta seguro que desea salir?", "SALIR", MessageBoxButtons.YesNo);
                if (result == DialogResult.No)
                {
                    e.Cancel = true;
                }
            }
        }

        private void Salircuent_Click(object sender, EventArgs e)
        {
            DialogResult result = MessageBox.Show("Esta seguro que desea salir?", "SALIR", MessageBoxButtons.YesNo);
            if (result == DialogResult.Yes)
            {
                this.usrClose = true;
                this.Close();
            }
        }
        #endregion
    }
}
